from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.index),
    path('studentlogin',views.studentlogin),
    path('studentsignup',views.studentsignup),
    path('studentdashboard',views.studentdashboard),
    path('facultydashboard',views.facultydashboard),
    path('hoddashboard',views.hoddashboard),
    path('studentsignup',views.studentsignup),
    path('parentlogin',views.parentlogin),
    path('parentsignup',views.parentsignup),
    path('facultylogin',views.facultylogin,name="facultylogin"),
    path('facultysignup',views.facultysignup,name="facultysignup"),
    path('hodlogin',views.hodlogin),
    path('hodsignup',views.hodsignup),
    path('officestafflogin',views.officestafflogin),
    path('officestaffsignup',views.officestaffsignup),
    path('officestaff1',views.officestaff1),
    path('studentlist',views.studentlist),
    path('officedashboard',views.officedashboard,name="officedashboard"),
    path('about',views.about),
    path('index',views.index),
    path('contact',views.contact),
    path('logout',views.logout),
    path('principallogin',views.principallogin),
    path('principaldashboard',views.principaldashboard),
    path('accept',views.accept,name="accept"),
    path('reject',views.reject,name='reject'),
    path('principaldashboard',views.principaldashboard,name="principaldashboard"),
    path('principal_addteachers',views.principal_addteachers,name="principal_addteachers"),
    path('principal_addhod',views.principal_addhod,name="principal_addhod"),
    path('principal_addofficestaff',views.principal_addofficestaff,name="principal_addofficestaff"),
    path('academic_calender',views.academic_calender,name="academic_calender"),
    path('principal_approvehod',views.principal_approvehod,name="principal_approvehod"),
    path('principal_approvefaculty',views.principal_approvefaculty,name="principal_approvefaculty"),
    path('principal_approveofficestaff',views.principal_approveofficestaff,name="principal_approveofficestaff"),
    path('principal_grievances',views.principal_grievances,name="principal_grievances"),
    path('principal_notice',views.principal_notice,name="principal_notice"),
    path('teacherprofile',views.teacherprofile,name="teacherprofile"),
    path('studentprofile',views.studentprofile,name="studentprofile"),
    path('facultyassingment',views.facultyassingment,name="facultyassingment"),
    path('grivence',views.grivence,name="grivence"),
    path('ffaccept',views.ffaccept,name="ffaccept"),
    path('ffreject',views.ffreject,name="ffreject"),
    path('busfeeupdate',views.busfeeupdate,name="busfeeupdate"),
    path('examfeeupdate',views.examfeeupdate,name="examfeeupdate"),
    path('haccept',views.haccept,name="haccept"),
    path('hreject',views.hreject,name='hreject'),


]