# Generated by Django 4.1.7 on 2023-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=10)),
                ('puserid', models.CharField(max_length=10)),
                ('ppassword1', models.CharField(max_length=10)),
                ('ppassword2', models.CharField(max_length=10)),
            ],
        ),
    ]
