# Generated by Django 4.1.7 on 2023-02-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='ppassword1',
            new_name='parent_cpassword',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='ppassword2',
            new_name='pemail',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='puserid',
            new_name='ppassword',
        ),
    ]
