# Generated by Django 4.1.7 on 2023-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_ppassword1_parent_parent_cpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('femail', models.CharField(max_length=10)),
                ('fpassword', models.CharField(max_length=10)),
                ('faculty_cpassword', models.CharField(max_length=10)),
            ],
        ),
    ]
