# Generated by Django 4.1.7 on 2023-02-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officestaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=10)),
                ('oemail', models.CharField(max_length=10)),
                ('opassword', models.CharField(max_length=10)),
                ('officestaff_cpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='faculty_cpassword',
            new_name='hemail',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='femail',
            new_name='hname',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='fname',
            new_name='hod_cpassword',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='fpassword',
            new_name='hpassword',
        ),
    ]
