# Generated by Django 4.1.7 on 2023-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_officestaff_rename_faculty_cpassword_hod_hemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
