# Generated by Django 4.1.7 on 2023-02-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_department_student_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
