# Generated by Django 4.1.7 on 2023-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_absent_student_percentage_student_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fdepartment',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
