# Generated by Django 4.1.7 on 2023-03-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_faculty_fdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fnumber',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='hdepartment',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='hnumber',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officestaff',
            name='onumber',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='pphonenumber',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
