# Generated by Django 4.1.7 on 2023-04-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officestaff',
            name='onumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
