# Generated by Django 4.1.7 on 2023-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentname',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
