# Generated by Django 4.1.7 on 2023-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_student_parentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=10)),
                ('present', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=10)),
                ('mothername', models.CharField(max_length=10)),
                ('guardianname', models.CharField(max_length=10)),
                ('guardianphn', models.CharField(max_length=10)),
                ('guardianemail', models.CharField(max_length=10)),
                ('yearofjoining', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('admissionno', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('admissiontype', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='parentname',
        ),
    ]
