# Generated by Django 4.1.7 on 2023-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_acceptedstudent_remove_student_parentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedstudent',
            name='semester',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
