# Generated by Django 4.1.7 on 2023-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_student_absent_remove_student_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptedfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('femail', models.CharField(max_length=10)),
                ('fdepartment', models.CharField(max_length=10)),
                ('fnumber', models.IntegerField(max_length=10)),
                ('fpassword', models.CharField(max_length=10)),
                ('faculty_cpassword', models.CharField(max_length=10)),
            ],
        ),
    ]
