# Generated by Django 4.1.7 on 2023-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_20230425_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grivence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=10)),
                ('gemail', models.CharField(max_length=100)),
                ('gsubject', models.CharField(max_length=100)),
                ('gmessage', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='acceptedfaculty',
            old_name='faculty_cpassword',
            new_name='ffaculty_cpassword',
        ),
        migrations.RenameField(
            model_name='acceptedfaculty',
            old_name='fdepartment',
            new_name='ffdepartment',
        ),
        migrations.RenameField(
            model_name='acceptedfaculty',
            old_name='femail',
            new_name='ffemail',
        ),
        migrations.RenameField(
            model_name='acceptedfaculty',
            old_name='fname',
            new_name='ffname',
        ),
        migrations.RenameField(
            model_name='acceptedfaculty',
            old_name='fnumber',
            new_name='ffnumber',
        ),
        migrations.RenameField(
            model_name='acceptedfaculty',
            old_name='fpassword',
            new_name='ffpassword',
        ),
        migrations.AlterField(
            model_name='acceptedstudent',
            name='userid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='officestaff',
            name='onumber',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
