# Generated by Django 4.1.7 on 2023-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_grivence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('hemail', models.CharField(max_length=100)),
                ('hnumber', models.IntegerField(max_length=100)),
                ('hdepartment', models.CharField(max_length=100)),
                ('hpassword', models.CharField(max_length=100)),
                ('hod_cpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='acceptedfaculty',
            name='ffaculty_cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acceptedfaculty',
            name='ffdepartment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acceptedfaculty',
            name='ffemail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acceptedfaculty',
            name='ffname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acceptedfaculty',
            name='ffnumber',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acceptedfaculty',
            name='ffpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fdepartment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='femail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fnumber',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hdepartment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hemail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hnumber',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hod_cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hpassword',
            field=models.CharField(max_length=100),
        ),
    ]
