# Generated by Django 4.1.7 on 2023-05-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_hdepartment_acceptedhod_hhdepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('busfees', models.IntegerField(max_length=10)),
            ],
        ),
    ]
