# Generated by Django 4.1.7 on 2023-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_acceptedstudent_bus_acceptedstudent_busfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedstudent',
            name='avl',
            field=models.IntegerField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
